name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: 13.61.2.143  # EC2 instance IP adresiniz
        username: ubuntu  # EC2 instance'ınızın kullanıcı adı (Amazon Linux için 'ec2-user', Ubuntu için 'ubuntu')
        key: ${{ secrets.EC2_KEY }}  # Private key'inizi GitHub Secrets'a ekleyin ve burada çağırın
        port: 22
        script: |
          cd /home/ubuntu  # Uygulamanın bulunduğu dizine gidin (örneğin /home/ubuntu/myapp)
          sudo su
          git pull
          npm install
          pm2 restart index.js  # Uygulamanızın giriş dosyasına göre güncelleyin, örneğin 'app.js' olabilir
